# Generated by Django 4.2 on 2023-05-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=100)),
                ('smark', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'marklist',
            },
        ),
    ]
